// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.7
// source: proto/enum/access_tier/v5/access_tier.proto

package v5

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessTier int32

const (
	AccessTier_ACCESS_TIER_UNSPECIFIED AccessTier = 0
	AccessTier_ACCESS_TIER_ARCHIVE     AccessTier = 1
	AccessTier_ACCESS_TIER_COOL        AccessTier = 2
	AccessTier_ACCESS_TIER_HOT         AccessTier = 3
)

// Enum value maps for AccessTier.
var (
	AccessTier_name = map[int32]string{
		0: "ACCESS_TIER_UNSPECIFIED",
		1: "ACCESS_TIER_ARCHIVE",
		2: "ACCESS_TIER_COOL",
		3: "ACCESS_TIER_HOT",
	}
	AccessTier_value = map[string]int32{
		"ACCESS_TIER_UNSPECIFIED": 0,
		"ACCESS_TIER_ARCHIVE":     1,
		"ACCESS_TIER_COOL":        2,
		"ACCESS_TIER_HOT":         3,
	}
)

func (x AccessTier) Enum() *AccessTier {
	p := new(AccessTier)
	*p = x
	return p
}

func (x AccessTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessTier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enum_access_tier_v5_access_tier_proto_enumTypes[0].Descriptor()
}

func (AccessTier) Type() protoreflect.EnumType {
	return &file_proto_enum_access_tier_v5_access_tier_proto_enumTypes[0]
}

func (x AccessTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessTier.Descriptor instead.
func (AccessTier) EnumDescriptor() ([]byte, []int) {
	return file_proto_enum_access_tier_v5_access_tier_proto_rawDescGZIP(), []int{0}
}

var File_proto_enum_access_tier_v5_access_tier_proto protoreflect.FileDescriptor

var file_proto_enum_access_tier_v5_access_tier_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x2f, 0x76, 0x35, 0x2f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76,
	0x35, 0x2a, 0x6d, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x69, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x17, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x49, 0x45, 0x52, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13,
	0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x49, 0x45, 0x52, 0x5f, 0x41, 0x52, 0x43, 0x48,
	0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f,
	0x54, 0x49, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4f, 0x4c, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x41,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x49, 0x45, 0x52, 0x5f, 0x48, 0x4f, 0x54, 0x10, 0x03,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x62, 0x69, 0x74, 0x6f, 0x66, 0x68, 0x65, 0x6c, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x69, 0x65, 0x72, 0x2f, 0x76, 0x35, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_enum_access_tier_v5_access_tier_proto_rawDescOnce sync.Once
	file_proto_enum_access_tier_v5_access_tier_proto_rawDescData = file_proto_enum_access_tier_v5_access_tier_proto_rawDesc
)

func file_proto_enum_access_tier_v5_access_tier_proto_rawDescGZIP() []byte {
	file_proto_enum_access_tier_v5_access_tier_proto_rawDescOnce.Do(func() {
		file_proto_enum_access_tier_v5_access_tier_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_enum_access_tier_v5_access_tier_proto_rawDescData)
	})
	return file_proto_enum_access_tier_v5_access_tier_proto_rawDescData
}

var file_proto_enum_access_tier_v5_access_tier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enum_access_tier_v5_access_tier_proto_goTypes = []interface{}{
	(AccessTier)(0), // 0: v5.AccessTier
}
var file_proto_enum_access_tier_v5_access_tier_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enum_access_tier_v5_access_tier_proto_init() }
func file_proto_enum_access_tier_v5_access_tier_proto_init() {
	if File_proto_enum_access_tier_v5_access_tier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_enum_access_tier_v5_access_tier_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enum_access_tier_v5_access_tier_proto_goTypes,
		DependencyIndexes: file_proto_enum_access_tier_v5_access_tier_proto_depIdxs,
		EnumInfos:         file_proto_enum_access_tier_v5_access_tier_proto_enumTypes,
	}.Build()
	File_proto_enum_access_tier_v5_access_tier_proto = out.File
	file_proto_enum_access_tier_v5_access_tier_proto_rawDesc = nil
	file_proto_enum_access_tier_v5_access_tier_proto_goTypes = nil
	file_proto_enum_access_tier_v5_access_tier_proto_depIdxs = nil
}
